### ISSUE TITLE
Clarification on context aware suggestions

### ISSUE THREAD

**Issue by dilini-muthumala** [TharinduMunasinge/CEP-Siddhi_Editor#3]
Hi,
After I have typed 'define' I see some additional suggestions such as 'instanceofinteger'. Please see the screenshot attached.
![context-aware-suggestions](https://cloud.githubusercontent.com/assets/7592890/9443607/9d989bd0-4a9f-11e5-9b3e-d2eb8bb0fc97.png)

I read in the discussion mail thread on dev, that a regex-based approach is being used to give context aware suggestions; hence thought to get a clarification on this.

Thank you,
Dilini

**Comment by tmun5718** [comment]
sure .. 
There are 3 modes of completions 
1) keyword completions ( keyword)
2) snippet completions ( snippet)
3) Context - sensitive completion ( intelli ) 

Context-sensitive completer generates the suggestions based on the context around the cursor position. They can be identified by "intelli" meta data shown next to the suggestion. If the current context can be identified and there are suitable suggestions , those suggestions + Keyword completions will be shown.  

Snippet completions are shown if the cursor is positioned in the beginning of a statement. ( consist of annotations, stream definitions , table definitions ... ) . They can be identified by the "snippet" meta data shown next to the suggestion. 

 Keyword completor include a static list of keywords and system functions . These suggestions will be shown by default (even though there are no suggestions from the above completors) .  

Design decision : Only the essential places will be addressed by Context sensitive auto completion.  Keywords are always listed to make a default suggestion in unchecked situation .

**Comment by dilini-muthumala** [comment]
@TharinduMunasinge Thanks a lot for the clarification!
