### ISSUE TITLE
annotation snippets not suggested when cursor placed after @Plan statements

### ISSUE THREAD

**Issue by dilini-muthumala** [TharinduMunasinge/CEP-Siddhi_Editor#4]
![annotations-are-not-suggested](https://cloud.githubusercontent.com/assets/7592890/9443918/7613eba8-4aa1-11e5-9f7b-0bd66753c1f5.png)

**Comment by tmun5718** [comment]
Thanks for pointing out the issue. 
Fixed in :  https://github.com/TharinduMunasinge/CEP-Siddhi_Editor/commit/02f9f05a776bfea469349d984a41c2c48724dd89

check : http://tharindumunasinge.github.io/CEP-Siddhi_Editor/eventprocessor/inner_execution_plan.ui.html

**Comment by dilini-muthumala** [comment]
Great!
