### ISSUE TITLE
Some snippets contain spaces

### ISSUE THREAD

**Issue by dilini-muthumala** [TharinduMunasinge/CEP-Siddhi_Editor#5]
For example,
@Export ("Stream_ID")

Please see the screenshot attached.
![annotations-contain-spaces](https://cloud.githubusercontent.com/assets/7592890/9443979/c40cb272-4aa1-11e5-8719-936ddf31cb0c.png)

Thank you,
Dilini

**Comment by tmun5718** [comment]
According to the CFG of Siddhi ( https://github.com/wso2/siddhi/blob/master/modules/siddhi-query-compiler/src/main/antlr4/org/wso2/siddhi/query/compiler/SiddhiQL.g4) it allows spaces in between the tokens of the annotation rule(correct me if I am wrong) . I think the error shown in this diagram related to a missing stream definition after the  annotation. Following query should be parsed by the syntax checker . 

 @Export   ("Stream_ID")
define stream foo ( bar int) ;

**Comment by dilini-muthumala** [comment]
Agreed and thanks for the clarification :+1: 
Just a small thing, to make things closer to perfection :) ,
When we have such spaces in between, syntax highlighting and tokenizing have to be taken care of.

For example, in the screenshot below, the Description is shown as an identifier:

![description-as-identifier](https://cloud.githubusercontent.com/assets/7592890/9450170/bffce5f8-4ac4-11e5-8a62-6282c72c2691.png)

**Comment by tmun5718** [comment]
Got the point :+1: 
Fixed in : https://github.com/TharinduMunasinge/CEP-Siddhi_Editor/issues/5

**Comment by dilini-muthumala** [comment]
Great! Thank you.
